version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      order-service:
        condition: service_healthy
      payments-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRINGDOC_API_DOCS_ENABLED: "true"
      SPRINGDOC_SWAGGER_UI_ENABLED: "true"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 90s

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "9091:9091"
    depends_on:
      order-service-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-service-db:5432/order-service
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 123
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 90s

  payments-service:
    build:
      context: ./payments-service
      dockerfile: Dockerfile
    container_name: payments-service
    ports:
      - "9090:9090"
    depends_on:
      payments-service-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://payments-service-db:5432/payments-service
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 123
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 90s


  order-service-db:
    image: postgres:15.15
    container_name: order-service-db
    environment:
      POSTGRES_DB: order-service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user || pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  payments-service-db:
    image: postgres:15.15
    container_name: payments-service-db
    environment:
      POSTGRES_DB: payments-service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - payments_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user || pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "29093:29093"
      - "9101:9101"
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka-init:
    image: confluentinc/cp-kafka:7.4.3
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      bash -c "
        kafka-topics --create --topic gozon.orders.v1 --bootstrap-server kafka:29092 --partitions 3 --replication-factor 1 &&
        kafka-topics --create --topic gozon.payments.v1 --bootstrap-server kafka:29092 --partitions 3 --replication-factor 1 &&
        echo 'Топики созданы!' &&
        kafka-topics --list --bootstrap-server kafka:9092
      "

volumes:
  order_db_data:
  payments_db_data:

